### ISSUE TITLE
Question on pre-tokenized input 

### ISSUE THREAD

**Issue by eliasyin** [nlp-uoregon/trankit#15]
In my case, I need to use bert to tokenize sentences and use trankit with the tokenized sentence  to calculate the dependency relations. I want to know whether trankit will have performance loss with the pre-tokenized sentence?

**Comment by minhhdvn** [comment]
Hi @eliasyin.
If you're using this [`BertTokenizer`](https://huggingface.co/transformers/model_doc/bert.html#berttokenizer), the performance loss would be significant. The reason is that `BertTokenizer` is used to split a sentence into wordpieces, which are not always actual words.
Dependency parsers in Trankit and other popular NLP toolkits (e.g., stanza, spacy) are trained on word-level data, that means they expect the pretokenized sentence to be a list of words.
I hope this answers your question.
Thanks.

**Comment by minhhdvn** [comment]
Hi @eliasyin,
Thanks for asking. 
Could you explain what you mean by "use bert to tokenize sentences"? 
Do you mean you want to get a list of words given a raw sentence string with a [BertTokenizer](https://huggingface.co/transformers/model_doc/bert.html#berttokenizer)?

**Comment by eliasyin** [comment]
> Hi @eliasyin,
> Thanks for asking.
> Could you explain what you mean by "use bert to tokenize sentences"?
> Do you mean you want to get a list of words given a raw sentence string with a [BertTokenizer](https://huggingface.co/transformers/model_doc/bert.html#berttokenizer)?

"use bert to tokenize sentences" means use BertTokenizer.

**Comment by minhhdvn** [comment]
> > Hi @eliasyin,
> > Thanks for asking.
> > Could you explain what you mean by "use bert to tokenize sentences"?
> > Do you mean you want to get a list of words given a raw sentence string with a [BertTokenizer](https://huggingface.co/transformers/model_doc/bert.html#berttokenizer)?
> 
> "use bert to tokenize sentences" means use BertTokenizer.
In this case,
We recommend you not using BertTokenizer to tokenize sentences.
The reason is that BertTokenizer splits a string into a list of wordpieces which are not always actual words.
For example, a usual tokenizer (of, e.g., trankit, spacy, stanza) would tokenize the sentence "I have a new GPU!" into:
["I", "have", "a", "new", "GPU", "!"]
This is the expected pretokenized sentence of Trankit for the dependency parser.
However, if you try using BertTokenizer to split the sentence, it would return:
["I", "have", "a", "new", "GP", "##U", "!"]
Here, the word "GPU" is split into two wordpieces "GP" and "##U".
For more information, you can look at this page: https://huggingface.co/transformers/tokenizer_summary.html

**Comment by eliasyin** [comment]
@minhhdvn Thank you
